# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "abd28d9097cfbd13e130b26f56ff468d"
name = "abdullahdev3"
handle = "abdullahdev3"
application_url = "https://annually-estimate-lamb-whilst.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://annually-estimate-lamb-whilst.trycloudflare.com/auth/callback",
  "https://annually-estimate-lamb-whilst.trycloudflare.com/auth/shopify/callback",
  "https://annually-estimate-lamb-whilst.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
