# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "316306505100eb403a3967b6474b1529"
name = "abdullahdev3"
handle = "abdullahdev3-3"
application_url = "https://shopify-sliderapp1.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-sliderapp1.onrender.com/auth/callback",
  "https://shopify-sliderapp1.onrender.com/auth/shopify/callback",
  "https://shopify-sliderapp1.onrender.com/api/auth/callback"

]

[pos]
embedded = false
