# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be2a6301d9971a58bffdbab097d0f318"
name = "demoapp"
handle = "demoapp-466"
application_url = "https://mandatory-meets-semester-ethics.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mandatory-meets-semester-ethics.trycloudflare.com/auth/callback",
  "https://mandatory-meets-semester-ethics.trycloudflare.com/auth/shopify/callback",
  "https://mandatory-meets-semester-ethics.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
