# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea3d6ff27bb1df8307d68076a65158c8"
name = "abdullahdev3"
handle = "abdullahdev3-7"
application_url = "https://similar-facial-evening-demographic.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://similar-facial-evening-demographic.trycloudflare.com/auth/callback",
  "https://similar-facial-evening-demographic.trycloudflare.com/auth/shopify/callback",
  "https://similar-facial-evening-demographic.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
