# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf7accda894ac7655919f84a7efd7911"
name = "SlideEase"
handle = "SlideEase"
application_url = "https://routines-neon-designing-contacted.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://routines-neon-designing-contacted.trycloudflare.com/auth/callback",
  "https://routines-neon-designing-contacted.trycloudflare.com/auth/shopify/callback",
  "https://routines-neon-designing-contacted.trycloudflare.com/api/auth/callback",
]

[pos]
embedded = false
