# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf7accda894ac7655919f84a7efd7911"
name = "SlideEase"
handle = "slideease"
application_url = "https://slideease.integritistudio.us"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://slideease.integritistudio.us/auth/callback",
  "https://slideease.integritistudio.us/auth/shopify/callback",
  "https://slideease.integritistudio.us/api/auth/callback"
]

[pos]
embedded = false
