/**
 * Ready-made slider templates (sample Unsplash placeholders — merchants replace with Files).
 */
const PLACEHOLDER = (seed) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=1600&q=80`

export const SLIDER_TEMPLATES = [
  {
    id: "black-friday",
    name: "Black Friday",
    description: "High-contrast sale hero with urgent CTAs",
    sliderType: "fade",
    settings: {
      autoplay: true,
      autoplaySpeed: 4000,
      arrows: true,
      dots: true,
      height: 480,
      borderRadius: 0,
      overlayOpacity: 0.45,
    },
    slides: [
      {
        title: "Black Friday",
        heading: "Up to 50% off",
        subheading: "Limited time only",
        description: "Shop our biggest sale of the year.",
        ctaText: "Shop the sale",
        ctaUrl: "/collections/all",
        imageUrl: PLACEHOLDER("1607083206869-4d797cf27ac4"),
        textAlign: "center",
        overlayColor: "#000000",
        overlayOpacity: 0.5,
        buttonBg: "#111111",
        buttonTextColor: "#ffffff",
      },
      {
        title: "Free shipping",
        heading: "Free shipping weekend",
        subheading: "No code needed",
        description: "Orders over $50 ship free.",
        ctaText: "Browse deals",
        ctaUrl: "/collections/all",
        imageUrl: PLACEHOLDER("1483985988355-763728e1935b"),
        textAlign: "left",
        overlayOpacity: 0.4,
        buttonBg: "#ef4444",
      },
    ],
  },
  {
    id: "new-arrivals",
    name: "New Arrivals",
    description: "Clean product drop layout for seasonal launches",
    sliderType: "center",
    settings: {
      autoplay: false,
      arrows: true,
      dots: true,
      height: 420,
      borderRadius: 16,
      centerMode: true,
    },
    slides: [
      {
        title: "New season",
        heading: "Just dropped",
        subheading: "Fresh styles for the season",
        ctaText: "Explore new",
        ctaUrl: "/collections/new",
        imageUrl: PLACEHOLDER("1441986300917-64674bd600d8"),
        textAlign: "center",
        buttonBg: "#0f766e",
      },
      {
        title: "Editor picks",
        heading: "Editor's picks",
        subheading: "Curated for you",
        ctaText: "View collection",
        ctaUrl: "/collections/all",
        imageUrl: PLACEHOLDER("1469334031218-e382a71b716b"),
        textAlign: "center",
        buttonBg: "#0f766e",
      },
    ],
  },
  {
    id: "lookbook",
    name: "Lookbook",
    description: "Editorial multi-item lookbook carousel",
    sliderType: "autoplay",
    settings: {
      autoplay: false,
      arrows: true,
      dots: false,
      slidesToShow: 3,
      height: 360,
      borderRadius: 12,
      infinite: true,
    },
    slides: [
      {
        title: "Look 1",
        heading: "City layers",
        ctaText: "Shop look",
        ctaUrl: "/collections/all",
        imageUrl: PLACEHOLDER("1490481651871-ab68de25d43d"),
        textAlign: "left",
        overlayOpacity: 0.25,
      },
      {
        title: "Look 2",
        heading: "Weekend ease",
        ctaText: "Shop look",
        ctaUrl: "/collections/all",
        imageUrl: PLACEHOLDER("1515886657613-9f3515b0c78f"),
        textAlign: "left",
        overlayOpacity: 0.25,
      },
      {
        title: "Look 3",
        heading: "Evening edit",
        ctaText: "Shop look",
        ctaUrl: "/collections/all",
        imageUrl: PLACEHOLDER("1509631179647-0177331693ae"),
        textAlign: "left",
        overlayOpacity: 0.25,
      },
    ],
  },
]
